[package]
name = "nes_emulator"
version = "0.1.0"
edition = "2021"

default-run = "emu"

[[bin]]
name = "emu"
path = "src/main.rs"

[[bin]]
name = "test"
path = "src/bin/test.rs"

[dependencies]
bitflags = "2.6.0"
lazy_static = "1.4.0"
rand = "0.8.5"
sdl2 = "0.36.0"
