use std::collections::HashMap;

use super::cpu::AddressingMode;
use lazy_static::lazy_static;

pub(super) struct Opcode {
    pub code: u8,
    pub mnemonic: &'static str,
    pub bytes: u8,
    pub _cycles: u8,
    pub mode: AddressingMode,
}

impl Opcode {
    pub fn new(
        _code: u8,
        mnemonic: &'static str,
        bytes: u8,
        _cycles: u8,
        mode: AddressingMode,
    ) -> Self {
        Self {
            code: _code,
            mnemonic,
            bytes,
            _cycles,
            mode,
        }
    }
}

fn op(
    opcode: u8,
    mnemonic: &'static str,
    bytes: u8,
    cycles: u8,
    mode: AddressingMode,
) -> (u8, Opcode) {
    (opcode, Opcode::new(opcode, mnemonic, bytes, cycles, mode))
}

lazy_static! {
    pub(super) static ref OPCODES: HashMap<u8, Opcode> = {
        HashMap::from([
            op(0x00, "BRK", 1, 7, AddressingMode::NoneAddressing),

            op(0x0B, "*AAC", 2, 2, AddressingMode::Immediate),
            op(0x2B, "*AAC", 2, 2, AddressingMode::Immediate),

            op(0x87, "*SAX", 2, 3, AddressingMode::ZeroPage),
            op(0x97, "*SAX", 2, 4, AddressingMode::ZeroPage_Y),
            op(0x83, "*SAX", 2, 6, AddressingMode::Indirect_X),
            op(0x8F, "*SAX", 3, 4, AddressingMode::Absolute),

            op(0x69, "ADC", 2, 2, AddressingMode::Immediate),
            op(0x65, "ADC", 2, 3, AddressingMode::ZeroPage),
            op(0x75, "ADC", 2, 4, AddressingMode::ZeroPage_X),
            op(0x6D, "ADC", 3, 4, AddressingMode::Absolute),
            op(0x7D, "ADC", 3, 4, AddressingMode::Absolute_X),
            op(0x79, "ADC", 3, 4, AddressingMode::Absolute_Y),
            op(0x61, "ADC", 2, 6, AddressingMode::Indirect_X),
            op(0x71, "ADC", 2, 5, AddressingMode::Indirect_Y),

            op(0x29, "AND", 2, 2, AddressingMode::Immediate),
            op(0x25, "AND", 2, 3, AddressingMode::ZeroPage),
            op(0x35, "AND", 2, 4, AddressingMode::ZeroPage_X),
            op(0x2D, "AND", 3, 4, AddressingMode::Absolute),
            op(0x3D, "AND", 3, 4, AddressingMode::Absolute_X),
            op(0x39, "AND", 3, 4, AddressingMode::Absolute_Y),
            op(0x21, "AND", 2, 6, AddressingMode::Indirect_X),
            op(0x31, "AND", 2, 5, AddressingMode::Indirect_Y),

            op(0x6B, "*ARR", 2, 2, AddressingMode::Immediate),

            op(0x0A, "ASL", 1, 2, AddressingMode::Accumulator),
            op(0x06, "ASL", 2, 5, AddressingMode::ZeroPage),
            op(0x16, "ASL", 2, 6, AddressingMode::ZeroPage_X),
            op(0x0E, "ASL", 3, 6, AddressingMode::Absolute),
            op(0x1E, "ASL", 3, 7, AddressingMode::Absolute_X),

            op(0x4B, "*ASR", 2, 2, AddressingMode::Immediate),

            op(0xAB, "*ATX", 2, 2, AddressingMode::Immediate),

            op(0x9F, "*AXA", 3, 5, AddressingMode::Absolute_Y),
            op(0x93, "*AXA", 2, 6, AddressingMode::Indirect_Y),

            op(0xCB, "*AXS", 2, 2, AddressingMode::Immediate),

            op(0x90, "BCC", 2, 2, AddressingMode::Relative),
            op(0xB0, "BCS", 2, 2, AddressingMode::Relative),
            op(0xF0, "BEQ", 2, 2, AddressingMode::Relative),
            op(0x24, "BIT", 2, 3, AddressingMode::ZeroPage),
            op(0x2C, "BIT", 3, 4, AddressingMode::Absolute),
            op(0x30, "BMI", 2, 2, AddressingMode::Relative),
            op(0xD0, "BNE", 2, 2, AddressingMode::Relative),
            op(0x10, "BPL", 2, 2, AddressingMode::Relative),
            op(0x50, "BVC", 2, 2, AddressingMode::Relative),
            op(0x70, "BVS", 2, 2, AddressingMode::Relative),
            op(0x18, "CLC", 1, 2, AddressingMode::Implied),
            op(0xD8, "CLD", 1, 2, AddressingMode::Implied),
            op(0x58, "CLI", 1, 2, AddressingMode::Implied),
            op(0xB8, "CLV", 1, 2, AddressingMode::Implied),
            op(0xC9, "CMP", 2, 2, AddressingMode::Immediate),
            op(0xC5, "CMP", 2, 3, AddressingMode::ZeroPage),
            op(0xD5, "CMP", 2, 4, AddressingMode::ZeroPage_X),
            op(0xCD, "CMP", 3, 4, AddressingMode::Absolute),
            op(0xDD, "CMP", 3, 4, AddressingMode::Absolute_X),
            op(0xD9, "CMP", 3, 4, AddressingMode::Absolute_Y),
            op(0xC1, "CMP", 2, 6, AddressingMode::Indirect_X),
            op(0xD1, "CMP", 2, 5, AddressingMode::Indirect_Y),
            op(0xE0, "CPX", 2, 2, AddressingMode::Immediate),
            op(0xE4, "CPX", 2, 3, AddressingMode::ZeroPage),
            op(0xEC, "CPX", 3, 4, AddressingMode::Absolute),
            op(0xC0, "CPY", 2, 2, AddressingMode::Immediate),
            op(0xC4, "CPY", 2, 3, AddressingMode::ZeroPage),
            op(0xCC, "CPY", 3, 4, AddressingMode::Absolute),

            op(0xC7, "*DCP", 2, 5, AddressingMode::ZeroPage),
            op(0xD7, "*DCP", 2, 6, AddressingMode::ZeroPage_X),
            op(0xCF, "*DCP", 3, 6, AddressingMode::Absolute),
            op(0xDF, "*DCP", 3, 7, AddressingMode::Absolute_X),
            op(0xDB, "*DCP", 3, 7, AddressingMode::Absolute_Y),
            op(0xC3, "*DCP", 2, 8, AddressingMode::Indirect_X),
            op(0xD3, "*DCP", 2, 8, AddressingMode::Indirect_Y),

            op(0xC6, "DEC", 2, 5, AddressingMode::ZeroPage),
            op(0xD6, "DEC", 2, 6, AddressingMode::ZeroPage_X),
            op(0xCE, "DEC", 3, 6, AddressingMode::Absolute),
            op(0xDE, "DEC", 3, 7, AddressingMode::Absolute_X),
            op(0xCA, "DEX", 1, 2, AddressingMode::Implied),
            op(0x88, "DEY", 1, 2, AddressingMode::Implied),

            op(0x04, "*DOP", 2, 3, AddressingMode::ZeroPage),
            op(0x14, "*DOP", 2, 4, AddressingMode::ZeroPage_X),
            op(0x34, "*DOP", 2, 4, AddressingMode::ZeroPage_X),
            op(0x44, "*DOP", 2, 3, AddressingMode::ZeroPage),
            op(0x54, "*DOP", 2, 4, AddressingMode::ZeroPage_X),
            op(0x64, "*DOP", 2, 3, AddressingMode::ZeroPage),
            op(0x74, "*DOP", 2, 4, AddressingMode::ZeroPage_X),
            op(0x80, "*DOP", 2, 2, AddressingMode::Immediate),
            op(0x82, "*DOP", 2, 2, AddressingMode::Immediate),
            op(0x89, "*DOP", 2, 2, AddressingMode::Immediate),
            op(0xC2, "*DOP", 2, 2, AddressingMode::Immediate),
            op(0xD4, "*DOP", 2, 4, AddressingMode::ZeroPage_X),
            op(0xE2, "*DOP", 2, 2, AddressingMode::Immediate),
            op(0xF4, "*DOP", 2, 4, AddressingMode::ZeroPage_X),

            op(0x49, "EOR", 2, 2, AddressingMode::Immediate),
            op(0x45, "EOR", 2, 3, AddressingMode::ZeroPage),
            op(0x55, "EOR", 2, 4, AddressingMode::ZeroPage_X),
            op(0x4D, "EOR", 3, 4, AddressingMode::Absolute),
            op(0x5D, "EOR", 3, 4, AddressingMode::Absolute_X),
            op(0x59, "EOR", 3, 4, AddressingMode::Absolute_Y),
            op(0x41, "EOR", 2, 6, AddressingMode::Indirect_X),
            op(0x51, "EOR", 2, 5, AddressingMode::Indirect_Y),
            op(0xE6, "INC", 2, 5, AddressingMode::ZeroPage),
            op(0xF6, "INC", 2, 6, AddressingMode::ZeroPage_X),
            op(0xEE, "INC", 3, 6, AddressingMode::Absolute),
            op(0xFE, "INC", 3, 7, AddressingMode::Absolute_X),
            op(0xE8, "INX", 1, 2, AddressingMode::Implied),
            op(0xC8, "INY", 1, 2, AddressingMode::Implied),

            op(0xE7, "*ISB", 2, 5, AddressingMode::ZeroPage),
            op(0xF7, "*ISB", 2, 6, AddressingMode::ZeroPage_X),
            op(0xEF, "*ISB", 3, 6, AddressingMode::Absolute),
            op(0xFF, "*ISB", 3, 7, AddressingMode::Absolute_X),
            op(0xFB, "*ISB", 3, 7, AddressingMode::Absolute_Y),
            op(0xE3, "*ISB", 2, 8, AddressingMode::Indirect_X),
            op(0xF3, "*ISB", 2, 8, AddressingMode::Indirect_Y),

            op(0x4C, "JMP", 3, 3, AddressingMode::Absolute),
            op(0x6C, "JMP", 3, 5, AddressingMode::Indirect),
            op(0x20, "JSR", 3, 6, AddressingMode::Absolute),

            op(0x02, "*KIL", 1, 0, AddressingMode::Implied),
            op(0x12, "*KIL", 1, 0, AddressingMode::Implied),
            op(0x22, "*KIL", 1, 0, AddressingMode::Implied),
            op(0x32, "*KIL", 1, 0, AddressingMode::Implied),
            op(0x42, "*KIL", 1, 0, AddressingMode::Implied),
            op(0x52, "*KIL", 1, 0, AddressingMode::Implied),
            op(0x62, "*KIL", 1, 0, AddressingMode::Implied),
            op(0x72, "*KIL", 1, 0, AddressingMode::Implied),
            op(0x92, "*KIL", 1, 0, AddressingMode::Implied),
            op(0xB2, "*KIL", 1, 0, AddressingMode::Implied),
            op(0xD2, "*KIL", 1, 0, AddressingMode::Implied),
            op(0xF2, "*KIL", 1, 0, AddressingMode::Implied),

            op(0xBB, "*LAR", 3, 4, AddressingMode::Absolute_Y),

            op(0xA7, "*LAX", 2, 3, AddressingMode::ZeroPage),
            op(0xB7, "*LAX", 2, 4, AddressingMode::ZeroPage_Y),
            op(0xAF, "*LAX", 3, 4, AddressingMode::Absolute),
            op(0xBF, "*LAX", 3, 4, AddressingMode::Absolute_Y),
            op(0xA3, "*LAX", 2, 6, AddressingMode::Indirect_X),
            op(0xB3, "*LAX", 2, 5, AddressingMode::Indirect_Y),

            op(0x1A, "*NOP", 1, 2, AddressingMode::Implied),
            op(0x3A, "*NOP", 1, 2, AddressingMode::Implied),
            op(0x5A, "*NOP", 1, 2, AddressingMode::Implied),
            op(0x7A, "*NOP", 1, 2, AddressingMode::Implied),
            op(0xDA, "*NOP", 1, 2, AddressingMode::Implied),
            op(0xFA, "*NOP", 1, 2, AddressingMode::Implied),

            op(0xA9, "LDA", 2, 2, AddressingMode::Immediate),
            op(0xA5, "LDA", 2, 3, AddressingMode::ZeroPage),
            op(0xB5, "LDA", 2, 4, AddressingMode::ZeroPage_X),
            op(0xAD, "LDA", 3, 4, AddressingMode::Absolute),
            op(0xBD, "LDA", 3, 4, AddressingMode::Absolute_X),
            op(0xB9, "LDA", 3, 4, AddressingMode::Absolute_Y),
            op(0xA1, "LDA", 2, 6, AddressingMode::Indirect_X),
            op(0xB1, "LDA", 2, 5, AddressingMode::Indirect_Y),
            op(0xA2, "LDX", 2, 2, AddressingMode::Immediate),
            op(0xA6, "LDX", 2, 3, AddressingMode::ZeroPage),
            op(0xB6, "LDX", 2, 4, AddressingMode::ZeroPage_Y),
            op(0xAE, "LDX", 3, 4, AddressingMode::Absolute),
            op(0xBE, "LDX", 3, 4, AddressingMode::Absolute_Y),
            op(0xA0, "LDY", 2, 2, AddressingMode::Immediate),
            op(0xA4, "LDY", 2, 3, AddressingMode::ZeroPage),
            op(0xB4, "LDY", 2, 4, AddressingMode::ZeroPage_X),
            op(0xAC, "LDY", 3, 4, AddressingMode::Absolute),
            op(0xBC, "LDY", 3, 4, AddressingMode::Absolute_X),
            op(0x4A, "LSR", 1, 2, AddressingMode::Accumulator),
            op(0x46, "LSR", 2, 5, AddressingMode::ZeroPage),
            op(0x56, "LSR", 2, 6, AddressingMode::ZeroPage_X),
            op(0x4E, "LSR", 3, 6, AddressingMode::Absolute),
            op(0x5E, "LSR", 3, 7, AddressingMode::Absolute_X),
            op(0xEA, "NOP", 1, 2, AddressingMode::Implied),
            op(0x09, "ORA", 2, 2, AddressingMode::Immediate),
            op(0x05, "ORA", 2, 2, AddressingMode::ZeroPage),
            op(0x15, "ORA", 2, 2, AddressingMode::ZeroPage_X),
            op(0x0D, "ORA", 3, 2, AddressingMode::Absolute),
            op(0x1D, "ORA", 3, 2, AddressingMode::Absolute_X),
            op(0x19, "ORA", 3, 2, AddressingMode::Absolute_Y),
            op(0x01, "ORA", 2, 2, AddressingMode::Indirect_X),
            op(0x11, "ORA", 2, 2, AddressingMode::Indirect_Y),
            op(0x48, "PHA", 1, 3, AddressingMode::Implied),
            op(0x08, "PHP", 1, 3, AddressingMode::Implied),
            op(0x68, "PLA", 1, 4, AddressingMode::Implied),
            op(0x28, "PLP", 1, 4, AddressingMode::Implied),

            op(0x27, "*RLA", 2, 5, AddressingMode::ZeroPage),
            op(0x37, "*RLA", 2, 6, AddressingMode::ZeroPage_X),
            op(0x2F, "*RLA", 3, 6, AddressingMode::Absolute),
            op(0x3F, "*RLA", 3, 7, AddressingMode::Absolute_X),
            op(0x3B, "*RLA", 3, 7, AddressingMode::Absolute_Y),
            op(0x23, "*RLA", 2, 8, AddressingMode::Indirect_X),
            op(0x33, "*RLA", 2, 8, AddressingMode::Indirect_Y),

            op(0x2A, "ROL", 1, 2, AddressingMode::Accumulator),
            op(0x26, "ROL", 2, 5, AddressingMode::ZeroPage),
            op(0x36, "ROL", 2, 6, AddressingMode::ZeroPage_X),
            op(0x2E, "ROL", 3, 6, AddressingMode::Absolute),
            op(0x3E, "ROL", 3, 7, AddressingMode::Absolute_X),
            op(0x6A, "ROR", 1, 2, AddressingMode::Accumulator),
            op(0x66, "ROR", 2, 5, AddressingMode::ZeroPage),
            op(0x76, "ROR", 2, 6, AddressingMode::ZeroPage_X),
            op(0x6E, "ROR", 3, 6, AddressingMode::Absolute),

            op(0x67, "*RRA", 2, 5, AddressingMode::ZeroPage),
            op(0x77, "*RRA", 2, 6, AddressingMode::ZeroPage_X),
            op(0x6F, "*RRA", 3, 6, AddressingMode::Absolute),
            op(0x7F, "*RRA", 3, 7, AddressingMode::Absolute_X),
            op(0x7B, "*RRA", 3, 7, AddressingMode::Absolute_Y),
            op(0x63, "*RRA", 2, 8, AddressingMode::Indirect_X),
            op(0x73, "*RRA", 2, 8, AddressingMode::Indirect_Y),

            op(0x7E, "ROR", 3, 7, AddressingMode::Absolute_X),
            op(0x40, "RTI", 1, 6, AddressingMode::Implied),
            op(0x60, "RTS", 1, 6, AddressingMode::Implied),
            op(0xE9, "SBC", 2, 2, AddressingMode::Immediate),
            op(0xE5, "SBC", 2, 3, AddressingMode::ZeroPage),
            op(0xF5, "SBC", 2, 4, AddressingMode::ZeroPage_X),
            op(0xED, "SBC", 3, 4, AddressingMode::Absolute),
            op(0xFD, "SBC", 3, 4, AddressingMode::Absolute_X),
            op(0xF9, "SBC", 3, 4, AddressingMode::Absolute_Y),
            op(0xE1, "SBC", 2, 6, AddressingMode::Indirect_X),
            op(0xF1, "SBC", 2, 5, AddressingMode::Indirect_Y),

            op(0xEB, "*SBC", 2, 2, AddressingMode::Immediate),

            op(0x38, "SEC", 1, 2, AddressingMode::Implied),
            op(0xF8, "SED", 1, 2, AddressingMode::Implied),
            op(0x78, "SEI", 1, 2, AddressingMode::Implied),

            op(0x07, "*SLO", 2, 5, AddressingMode::ZeroPage),
            op(0x17, "*SLO", 2, 6, AddressingMode::ZeroPage_X),
            op(0x0F, "*SLO", 3, 6, AddressingMode::Absolute),
            op(0x1F, "*SLO", 3, 7, AddressingMode::Absolute_X),
            op(0x1B, "*SLO", 3, 7, AddressingMode::Absolute_Y),
            op(0x03, "*SLO", 2, 8, AddressingMode::Indirect_X),
            op(0x13, "*SLO", 2, 8, AddressingMode::Indirect_Y),

            op(0x47, "*SRE", 2, 5, AddressingMode::ZeroPage),
            op(0x57, "*SRE", 2, 6, AddressingMode::ZeroPage_X),
            op(0x4F, "*SRE", 3, 6, AddressingMode::Absolute),
            op(0x5F, "*SRE", 3, 7, AddressingMode::Absolute_X),
            op(0x5B, "*SRE", 3, 7, AddressingMode::Absolute_Y),
            op(0x43, "*SRE", 2, 8, AddressingMode::Indirect_X),
            op(0x53, "*SRE", 2, 8, AddressingMode::Indirect_Y),

            op(0x85, "STA", 2, 3, AddressingMode::ZeroPage),
            op(0x95, "STA", 2, 4, AddressingMode::ZeroPage_X),
            op(0x8D, "STA", 3, 4, AddressingMode::Absolute),
            op(0x9D, "STA", 3, 5, AddressingMode::Absolute_X),
            op(0x99, "STA", 3, 5, AddressingMode::Absolute_Y),
            op(0x81, "STA", 2, 6, AddressingMode::Indirect_X),
            op(0x91, "STA", 2, 6, AddressingMode::Indirect_Y),
            op(0x86, "STX", 2, 3, AddressingMode::ZeroPage),
            op(0x96, "STX", 2, 4, AddressingMode::ZeroPage_Y),
            op(0x8E, "STX", 3, 4, AddressingMode::Absolute),
            op(0x84, "STY", 2, 3, AddressingMode::ZeroPage),
            op(0x94, "STY", 2, 4, AddressingMode::ZeroPage_X),
            op(0x8C, "STY", 3, 4, AddressingMode::Absolute),

            op(0x9E, "*SXA", 3, 5, AddressingMode::Absolute_Y),

            op(0x9C, "*SYA", 3, 5, AddressingMode::Absolute_X),

            op(0xAA, "TAX", 1, 2, AddressingMode::Implied),
            op(0xA8, "TAY", 1, 2, AddressingMode::Implied),

            op(0x0C, "*TOP", 3, 4, AddressingMode::Absolute),
            op(0x1C, "*TOP", 3, 4, AddressingMode::Absolute_X),
            op(0x3C, "*TOP", 3, 4, AddressingMode::Absolute_X),
            op(0x5C, "*TOP", 3, 4, AddressingMode::Absolute_X),
            op(0x7C, "*TOP", 3, 4, AddressingMode::Absolute_X),
            op(0xDC, "*TOP", 3, 4, AddressingMode::Absolute_X),
            op(0xFC, "*TOP", 3, 4, AddressingMode::Absolute_X),

            op(0xBA, "TSX", 1, 2, AddressingMode::Implied),
            op(0x8A, "TXA", 1, 2, AddressingMode::Implied),
            op(0x9A, "TXS", 1, 2, AddressingMode::Implied),
            op(0x98, "TYA", 1, 2, AddressingMode::Implied),

            op(0x8B, "*XAA", 2, 2, AddressingMode::Immediate), //TODO

            op(0x9B, "*XAS", 3, 5, AddressingMode::Absolute_Y),
        ])
    };
}
